### ISSUE TITLE
Submit actions to the Fastlane repository

### ISSUE THREAD

**Issue by andreshj87** [appfoundry/fastlane-android-example#1]
Have you consider submitting your [actions](https://github.com/appfoundry/fastlane-android-example/tree/master/sample/fastlane/actions) to the Fastlane main repository?
This way, they will be listed when **fastlane search_plugins** is executed, and they would be easily installable via:
**fastlane add_plugin sign_apk**
**fastlane add_plugin zipalign**

It's really easy to publish your actions, check this out:
https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md#publishing-your-plugin

**Comment by mehcode** [comment]
@nomisRev Any chance of this happening? It'd be great to have these in the plugin registry.

**Comment by mehcode** [comment]
Nevermind. For future reference: @Zireck @bartvandeweerdt  @nomisRev 

```
    gradle(
      task: "assembleRelease",
      properties: {
        "android.injected.signing.store.file" => "...",
        "android.injected.signing.store.password" => "...",
        "android.injected.signing.key.alias" => "...",
        "android.injected.signing.key.password" => "...",
      }
    )
```

That just works now.

**Comment by bartvandeweerdt** [comment]
Hi, good idea! We'll try to find some time to make this happen. Great to see that you have a workaround in the meantime.

**Comment by sannysinghs** [comment]
@mehcode , thanks it save time. just curiosity, how one will know about these key existence ?  such as android.injected.signing..... . Or it is custom properties ?

**Comment by janpio** [comment]
@mehcode: What an awesome find! I created a PR for the `gradle` docs at Fastlane so this gets more known: https://github.com/fastlane/fastlane/pull/10938

@sannysinghs In this case, this old blog post is one of the most prominent sources of this knowledge: http://www.tinmith.net/wayne/blog/2014/08/gradle-sign-command-line.htm

**Comment by janpio** [comment]
> janpio unassigned nomisRev a minute ago

Uh what? How did I do that by commenting?

**Comment by bartvandeweerdt** [comment]
Thanks for your interest in our Fastlane Android example. However, due to a change of direction in how we decided to include Android in our Fastlane setup we are no longer maintaining this repository.
