### ISSUE TITLE
jarsigner is broken

### ISSUE THREAD

**Issue by StobyWan** [appfoundry/fastlane-android-example#10]
Unknown method 'user_error', supported [:select, :message, :verbose, :error, :password, :input, :important, :command, :deprecated, :command_output, :user_error!, :interactive?, :crash!, :confirm, :header, :success, :not_implemented, :shell_error!, :build_failure!, :test_failure!, :abort_with_message!]

**Comment by bartvandeweerdt** [comment]
Thanks for your interest in our Fastlane Android example. However, due to a change of direction in how we decided to include Android in our Fastlane setup we are no longer maintaining this repository.
