### ISSUE TITLE
sign_apk broken with Fastlane 2.68.2: jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1: command not found

### ISSUE THREAD

**Issue by egr-ext** [appfoundry/fastlane-android-example#11]
Hi,

With Fastlane 2.62, the command sign_apk works fine.
If I upgrade Fastlane to 2.68.2, I have an error :
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1: command not found

What is the solution ?

**Comment by opetrovskyi** [comment]
+1

seems like cmd command is not executed in one line and .shellescape do not do the trick.

**Comment by monday8am** [comment]
I'm not an expert in Ruby or Fastlane internals. In this case, seems to be that this [command](https://github.com/appfoundry/fastlane-android-example/blob/master/fastlane%20actions/sign_apk.rb#L30) changed and it doesn't accept string arrays. Just change this line to:
`Fastlane::Actions.sh(sign_cmd.join(" "), log: true)` 

and it will work again (at least for me :) )

**Comment by opetrovskyi** [comment]
I'm not a ruby guy at all but found exactly the same solution.

Fastlane::Actions.sh( sign_cmd.join(' '), log: true)

**Comment by egr-ext** [comment]
Thaks a lot, do we create a Pull Request ?

**Comment by flatsteve** [comment]
Anyone facing an issue with the zipalign action after upgrading fastlane? 

I'm getting: `Shell command exited with exit status 2 instead of 0`

Just wondering if it's a similar issue to that mentioned above (which fixed my problem with jarsigner).

**Comment by flatsteve** [comment]
Just a heads up, the `zipalign` action needs similar alterations (thanks to @monday8am for the original fix!):

`zipalign.rb`
Line 15: `Fastlane::Actions.sh(rename_command.join(" "), log: false)`
Line 18: `Fastlane::Actions.sh(aligncmd.join(" "), log: true)`

**Comment by bartvandeweerdt** [comment]
Hi everyone! We've noticed the activity here and would like you to know we'll be picking this up asap. Thanks for your input. Much appreciated!

**Comment by jaranflaath** [comment]
The solutions outlined fixed the error "wrong first argument" which I got from both sign_apk and zipalign when using fastlane 2.69 and newer.
