### ISSUE TITLE
Wrapping the alias command in single quotes breaks on windows

### ISSUE THREAD

**Issue by libbyrobinson** [appfoundry/fastlane-android-example#12]
This change:
https://github.com/appfoundry/fastlane-android-example/commit/820684a0842d57594931588df7aff48e93de7d8f#diff-21741517e25e3a1b5aed849e3996f265
was added to support whitespaces in alias'. 

We had a lot of frustration running Fastlane commands on windows using this, and you will end up with and error coming out of jarsigner, `jarsigner: Certificate chain not found for: 'distribution'.  'distribution' must reference a valid KeyStore key entry containing a private key and corresponding public key certificate chain.`, where `'distribution'` is the literal being passed into that command. 

You can repro this in the windows command shell with a jarsigner command like `jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore keystores\distribution.jks platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk 'distribution' -keypass Password -storepass Password -tsa http://timestamp.comodoca.com/rfc316 -signedjar platforms/android/app/build/outputs/apk/release/app-release.apk`. You will get the same output. 

Putting this here for anyone else running into this issue, that we got around this by removing the single quotes around alias.

**Comment by bartvandeweerdt** [comment]
Thanks @libbyrobinson !
Just like to let you know that, due to a change of direction in how we decided to include Android in our Fastlane setup, we are no longer maintaining this repository.
