### ISSUE TITLE
Zipalign conflict

### ISSUE THREAD

**Issue by mkiisoft** [appfoundry/fastlane-android-example#6]
Hello guys! I'm getting the following error with zipalign. When running fastlane action zipalign it shows me the correct data and that can be located but when I run my fastlane to compile, this is what I get:

```
```| 💥   | zipalign                            | 0           |
+------+-------------------------------------+-------------+

[13:32:34]: fastlane finished with errors

[13:32:34]: Error accessing file, this might be due to fastlane's directory handling
[13:32:34]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details

/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.25.0/fastlane/lib/fastlane/helper/sh_helper.rb:36:in `popen': No such file or directory - zipalign (Errno::ENOENT) ```
```

My Fastlane file and actions folder looks exactly the same as yours.

My bash.profile also looks good getting access to the zipalign binary from google apis:

```
export ANDROID_HOME=/Users/{user}/Library/Android/sdk/
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$ANDROID_HOME/tools:$PATH
export ANDROID_BUILD_TOOLS=$ANDROID_HOME/build-tools/22.0.1/:$PATH
```

**Comment by blazmag** [comment]
Had the same error. Adding zipalign to PATH helped resolve the issue although I see you're already doing that. Doublecheck if you can run zipalign from terminal ?

**Comment by bartvandeweerdt** [comment]
Thanks for your interest in our Fastlane Android example. However, due to a change of direction in how we decided to include Android in our Fastlane setup we are no longer maintaining this repository.
