### ISSUE TITLE
zipalign does not zipalign all platform apks(splits apks)

### ISSUE THREAD

**Issue by adiget** [appfoundry/fastlane-android-example#7]
Hi,I have set up for splits apks, which generates 4 platforms("armeabi", "armeabi-v7a", "x86", "x86_64") apks. I am not able to zipalign for all these apks.

I think, this Line on Fastfile only zipalign the last apk of the all abi apks.
zipalign(apk_path: "#{lane_context[SharedValues::SIGNED_APK_PATH]}")

How to make it zipalign for all apks from GRADLE_ALL_APK_OUTPUT_PATHS?

**Comment by bartvandeweerdt** [comment]
Thanks for your interest in our Fastlane Android example. However, due to a change of direction in how we decided to include Android in our Fastlane setup we are no longer maintaining this repository.
