### ISSUE TITLE
Convert actions to Fastlane plugins

### ISSUE THREAD

**Issue by janpio** [appfoundry/fastlane-android-example#8]
These two actions would make excellent candidates for a "Sign your Android App" Fastlane plugin.

Creating Fastlane plugins is pretty easy, especially if you already have the actions ready and tested:
https://docs.fastlane.tools/plugins/create-plugin/

Would you be interested in having your actions converted into a Fastlane plugin?

**Comment by alexanderritola** [comment]
This would be very helpful!

**Comment by bartvandeweerdt** [comment]
Thanks for your interest in our Fastlane Android example. However, due to a change of direction in how we decided to include Android in our Fastlane setup we are no longer maintaining this repository.
