### ISSUE TITLE
Couldn't find '*release-unsigned.apk'

### ISSUE THREAD

**Issue by Dudu-Cohen** [appfoundry/fastlane-android-example#9]
13:45:40]: fastlane finished with errors

[!] Couldn't find '*release-unsigned.apk' file at path 'app/build/outputs/apk/'
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by bartvandeweerdt** [comment]
Thanks for your interest in our Fastlane Android example. However, due to a change of direction in how we decided to include Android in our Fastlane setup we are no longer maintaining this repository.
